name: CI

on:
    pull_request:
        types: [assigned, opened, synchronize, reopened]
    pull_request_review:
        types: [edited, dismissed]
    pull_request_review_comment:
        types: [created, deleted]
    push:

jobs:
    build:
        runs-on: windows-latest

        env:
            Solution_Name: ./Pixeval.sln
            Project_Path: ./src/Pixeval/Pixeval.csproj
            Configuration: Release
            Platform: x64

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Setup .NET SDK
              uses: actions/setup-dotnet@v1.7.2
              with:
                 dotnet-version: '5.0.100-rc.1.20452.10'

            - name: Cache nuget packages
              id: cache-nuget
              uses: actions/cache@v2
              with:
                  path: ~/.nuget/packages
                  key: ${{ runner.os }}-nuget-${{ hashFiles('**/Pixeval.csproj') }}
                  restore-keys: |
                      ${{ runner.os }}-nuget-

            - name: Build the application
              run: dotnet build $env:Project_Path -p:Configuration=$env:Configuration -p:Platform=$env:Platform /m

            - name: Publish the application
              run: dotnet publish $env:Project_Path -p:OutDir="$PWD/publish" -p:Configuration=$env:Configuration -p:Platform=$env:Platform -m

            - name: Copy dotnet-install.ps1 to publish dir
              run: Copy-Item -Path ./dotnet-install.ps1 -Destination ./publish/dotnet-install.ps1
              
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: Pixeval
                  path: "./publish/*"
